with card_content(display_order, question_text, question_translation, answer_examples) as (
  values
    (41, 'Do you play any musical instruments?', 'Você toca algum instrumento musical?', '[{"answer":"Yes, I play the guitar.","translation":"Sim, eu toco violão.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I play a little piano.","translation":"Eu toco um pouco de piano.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"No, I don''t play any instruments.","translation":"Não, eu não toco nenhum instrumento.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"I used to play the drums.","translation":"Eu costumava tocar bateria.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I''m learning how to play the keyboard.","translation":"Eu estou aprendendo a tocar teclado.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (42, 'Do you like sports?', 'Você gosta de esportes?', '[{"answer":"Yes, I love sports.","translation":"Sim, eu adoro esportes.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"Yes, especially soccer.","translation":"Sim, especialmente futebol.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I like watching sports more than playing them.","translation":"Eu gosto mais de assistir a esportes do que praticá-los.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"Not very much.","translation":"Não muito.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I enjoy sports, but I don''t follow any team closely.","translation":"Eu gosto de esportes, mas não acompanho nenhum time de perto.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (43, 'What is your favorite sport?', 'Qual é o seu esporte favorito?', '[{"answer":"My favorite sport is soccer.","translation":"Meu esporte favorito é futebol.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I really like volleyball.","translation":"Eu gosto muito de vôlei.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I prefer basketball.","translation":"Eu prefiro basquete.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"Swimming is my favorite sport.","translation":"Natação é o meu esporte favorito.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I don''t have a favorite, but I enjoy several sports.","translation":"Eu não tenho um favorito, mas gosto de vários esportes.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (44, 'Do you play any sports?', 'Você pratica algum esporte?', '[{"answer":"Yes, I play soccer.","translation":"Sim, eu jogo futebol.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I play volleyball once a week.","translation":"Eu jogo vôlei uma vez por semana.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I go swimming regularly.","translation":"Eu nado regularmente.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"No, I don''t play any sports right now.","translation":"Não, eu não pratico nenhum esporte no momento.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I occasionally play tennis with friends.","translation":"Eu jogo tênis com amigos de vez em quando.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (45, 'Do you exercise regularly?', 'Você se exercita regularmente?', '[{"answer":"Yes, I exercise three times a week.","translation":"Sim, eu me exercito três vezes por semana.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I work out almost every day.","translation":"Eu treino quase todos os dias.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I try to exercise on weekends.","translation":"Eu tento me exercitar nos fins de semana.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"Not as regularly as I''d like.","translation":"Não tão regularmente quanto eu gostaria.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I usually walk or cycle a few times a week.","translation":"Eu geralmente caminho ou pedalo algumas vezes por semana.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (46, 'Do you go to the gym?', 'Você vai à academia?', '[{"answer":"Yes, I go three times a week.","translation":"Sim, eu vou três vezes por semana.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I go to the gym after work.","translation":"Eu vou à academia depois do trabalho.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"Sometimes, but not every week.","translation":"Às vezes, mas não toda semana.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"No, I prefer exercising outdoors.","translation":"Não, eu prefiro me exercitar ao ar livre.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I used to go, but now I work out at home.","translation":"Eu costumava ir, mas agora treino em casa.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (47, 'What is your favorite food?', 'Qual é a sua comida favorita?', '[{"answer":"My favorite food is pizza.","translation":"Minha comida favorita é pizza.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I love Brazilian barbecue.","translation":"Eu adoro churrasco brasileiro.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I really like pasta.","translation":"Eu gosto muito de massas.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"Japanese food is my favorite.","translation":"Comida japonesa é a minha favorita.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"It''s hard to choose, but I probably like homemade food the most.","translation":"É difícil escolher, mas provavelmente gosto mais de comida caseira.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (48, 'What food do you dislike?', 'De que comida você não gosta?', '[{"answer":"I don''t like olives.","translation":"Eu não gosto de azeitonas.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"I dislike very spicy food.","translation":"Eu não gosto de comida muito apimentada.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I''m not a big fan of seafood.","translation":"Eu não sou muito fã de frutos do mar.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"I don''t really like liver.","translation":"Eu realmente não gosto de fígado.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"There aren''t many foods I dislike, but I avoid very greasy dishes.","translation":"Não há muitas comidas de que eu não goste, mas evito pratos muito gordurosos.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (49, 'Can you cook?', 'Você sabe cozinhar?', '[{"answer":"Yes, I can.","translation":"Sim, eu sei.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"Yes, I cook almost every day.","translation":"Sim, eu cozinho quase todos os dias.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"A little. I can make simple meals.","translation":"Um pouco. Eu sei fazer refeições simples.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"Not very well, but I''m learning.","translation":"Não muito bem, mas estou aprendendo.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"Yes, and I really enjoy trying new recipes.","translation":"Sim, e eu gosto muito de experimentar receitas novas.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb),
    (50, 'What is your favorite dish to cook?', 'Qual é o seu prato favorito de preparar?', '[{"answer":"I like cooking pasta.","translation":"Eu gosto de preparar massas.","note":"Resposta direta e neutra, adequada para a maioria das situações."},{"answer":"My favorite dish to make is risotto.","translation":"Meu prato favorito de preparar é risoto.","note":"Opção natural e informal para conversas do dia a dia."},{"answer":"I enjoy making homemade pizza.","translation":"Eu gosto de fazer pizza caseira.","note":"Resposta um pouco mais detalhada, útil para manter a conversa."},{"answer":"I usually cook rice, beans, and chicken.","translation":"Eu geralmente preparo arroz, feijão e frango.","note":"Alternativa que acrescenta contexto e ajuda a desenvolver a interação."},{"answer":"I love making desserts, especially chocolate cake.","translation":"Eu adoro fazer sobremesas, especialmente bolo de chocolate.","note":"Resposta mais pessoal ou específica para quando você quiser elaborar."}]'::jsonb)
)
update public.conversation_questions as question
set
  question_text = content.question_text,
  question_translation = content.question_translation,
  answer_examples = content.answer_examples
from card_content as content
where question.display_order = content.display_order;
