insert into public.page_content_overrides (page_key, content, updated_at)
values (
  'aula-particular-ou-em-grupo',
  jsonb_build_object(
    'hero_eyebrow', 'Escolha do formato',
    'hero_title', 'Aula de inglês particular ou em grupo: qual escolher?',
    'hero_intro', 'A aula particular oferece máxima personalização. A aula em grupo acrescenta interação com outros estudantes e costuma ter custo menor. A melhor escolha depende do objetivo.',
    'short_answer_label', 'Resposta curta',
    'short_answer_text', 'Escolha aula particular quando precisar de um plano altamente específico, ritmo totalmente individual ou preparação urgente. Escolha um grupo pequeno quando quiser combinar acompanhamento do professor, prática com outras pessoas e melhor relação entre custo e interação.',
    'private_title', 'O que a aula particular faz melhor?',
    'private_p1', 'Na aula individual, todo o tempo pode ser adaptado ao estudante. O professor consegue ajustar vocabulário, ritmo, tarefas e correções a um objetivo muito específico. Isso é especialmente útil em preparação para entrevista, apresentação, prova oral ou necessidade profissional especializada.',
    'private_p2', 'Também é um formato adequado para quem tem disponibilidade de horário difícil ou precisa avançar em pontos muito diferentes daqueles de uma turma regular.',
    'group_title', 'O que a aula em grupo faz melhor?',
    'group_p1', 'Uma língua não é usada apenas em interação com um professor. Em um grupo, o aluno precisa compreender pessoas diferentes, esperar turnos, fazer perguntas, pedir esclarecimentos e sustentar uma conversa. Esse componente social é pedagogicamente valioso.',
    'group_p2', 'Quando o grupo é pequeno, é possível preservar boa parte do acompanhamento individual sem perder a variedade de interlocutores. Além disso, o custo por aluno tende a ser menor.',
    'comparison_title', 'Comparação por critério',
    'comparison_label_1', 'Personalização:',
    'comparison_text_1', 'vantagem da aula particular.',
    'comparison_label_2', 'Variedade de interlocutores:',
    'comparison_text_2', 'vantagem da aula em grupo.',
    'comparison_label_3', 'Flexibilidade de horário:',
    'comparison_text_3', 'geralmente maior na aula particular.',
    'comparison_label_4', 'Custo:',
    'comparison_text_4', 'geralmente menor no grupo.',
    'comparison_label_5', 'Prática de interação social:',
    'comparison_text_5', 'maior no grupo.',
    'comparison_label_6', 'Objetivos muito específicos:',
    'comparison_text_6', 'mais fáceis de atender individualmente.',
    'beginner_title', 'Para iniciantes, qual formato é melhor?',
    'beginner_p1', 'Os dois formatos podem funcionar. Um iniciante não precisa necessariamente de aula individual. Em um grupo pequeno e nivelado, tarefas simples podem ser repetidas com diferentes colegas, o que ajuda a automatizar estruturas básicas.',
    'beginner_p2', 'O aspecto mais importante é o professor controlar a dificuldade e garantir que nenhum aluno passe a aula inteira apenas observando os outros.',
    'conversation_title', 'Para quem quer conversação, qual formato é melhor?',
    'conversation_p1', 'Em muitos casos, um grupo pequeno oferece uma vantagem: o estudante conversa com mais de uma pessoa. Isso aproxima a prática da imprevisibilidade da comunicação real. A aula particular, por outro lado, permite concentrar toda a conversa em temas e dificuldades de um único aluno.',
    'conversation_p2', 'Por isso, a pergunta correta não é “qual é sempre melhor?”, mas “qual variável é mais importante para meu objetivo agora?”.',
    'rule_title', 'Uma regra prática',
    'rule_p1', 'Se você precisa de máxima personalização, escolha individual. Se busca prática recorrente, interação, acompanhamento e menor custo, considere um grupo pequeno. Se ainda estiver em dúvida, uma aula experimental é uma forma melhor de decidir do que apenas comparar descrições comerciais.',
    'related_title', 'Leituras relacionadas',
    'related_link_1', 'Como escolher um curso de inglês online?',
    'related_link_2', 'Aulas em grupos pequenos funcionam?',
    'cta_title', 'Quer experimentar um grupo pequeno?',
    'cta_text', 'As turmas do Teacher Flávio têm até quatro alunos e aulas online ao vivo.',
    'cta_button', 'Conhecer o formato'
  ),
  now()
)
on conflict (page_key) do nothing;