insert into public.page_content_overrides (page_key, content, updated_at)
values (
  'aulas-de-ingles-em-grupos-pequenos',
  jsonb_build_object(
    'hero_eyebrow', 'Formato de aula',
    'hero_title', 'Aulas de inglês em grupos pequenos funcionam?',
    'hero_intro', 'Sim, podem funcionar muito bem quando o grupo é realmente reduzido, há tempo de fala para todos e o professor consegue acompanhar a produção de cada estudante.',
    'short_answer_label', 'Resposta curta',
    'short_answer_text', 'Grupos pequenos tendem a equilibrar duas vantagens: interação com outros alunos e possibilidade de acompanhamento individual. O tamanho do grupo, porém, precisa permitir participação frequente. Um grupo pequeno que funciona bem não é apenas uma turma grande com menos pessoas.',
    'size_title', 'Por que o tamanho da turma importa?',
    'size_p1', 'Em uma aula de língua, uma parte importante do aprendizado acontece quando o estudante precisa formular uma resposta, negociar significado, fazer perguntas, reformular uma frase e reagir ao que outra pessoa disse. Quanto maior a turma, mais difícil é distribuir esse tempo de produção oral.',
    'size_p2', 'Em grupos reduzidos, o professor consegue organizar pares, rodadas de perguntas, tarefas colaborativas e momentos de feedback sem transformar a aula em uma sequência de longas esperas. O estudante também tende a conhecer melhor os colegas, o que pode diminuir a sensação de exposição ao falar.',
    'advantages_title', 'Quais são as principais vantagens?',
    'advantage_label_1', 'Mais oportunidades de fala:',
    'advantage_text_1', 'cada aluno precisa participar várias vezes durante a aula.',
    'advantage_label_2', 'Interação real:',
    'advantage_text_2', 'o estudante não conversa apenas com o professor; precisa compreender e responder a outras pessoas.',
    'advantage_label_3', 'Feedback mais próximo:',
    'advantage_text_3', 'o professor consegue observar padrões de erro e orientar cada participante.',
    'advantage_label_4', 'Aprendizagem por observação:',
    'advantage_text_4', 'ouvir dúvidas e soluções dos colegas também produz aprendizagem.',
    'advantage_label_5', 'Custo compartilhado:',
    'advantage_text_5', 'normalmente o formato de grupo permite mensalidade menor do que uma aula individual.',
    'limits_title', 'Quando grupos pequenos podem não ser a melhor opção?',
    'limits_p1', 'Um estudante com objetivo muito específico e urgente pode se beneficiar de aulas individuais. É o caso de quem precisa preparar uma entrevista em poucos dias, revisar uma apresentação técnica ou trabalhar uma dificuldade altamente particular.',
    'limits_p2', 'Também pode haver incompatibilidade quando os participantes têm níveis muito diferentes. Um bom grupo não exige que todos saibam exatamente as mesmas coisas, mas a diferença não pode ser tão grande a ponto de a atividade ser trivial para uns e incompreensível para outros.',
    'observe_title', 'O que observar antes de escolher uma turma?',
    'observe_item_1', 'Quantos alunos participam efetivamente de cada aula?',
    'observe_item_2', 'A aula é ao vivo ou apenas conteúdo gravado com encontros ocasionais?',
    'observe_item_3', 'Há atividades em que o estudante fala e produz inglês?',
    'observe_item_4', 'O professor oferece feedback durante ou depois das atividades?',
    'observe_item_5', 'Existe algum plano de estudo para o período entre as aulas?',
    'observe_followup', 'Essas perguntas são mais úteis do que avaliar apenas o número de horas contratadas. Uma hora de aula em que o aluno participa ativamente pode ter uma dinâmica muito diferente de uma hora em que ele apenas assiste.',
    'self_study_title', 'Grupo pequeno substitui o estudo individual?',
    'self_study_p1', 'Não. A aula organiza a aprendizagem e cria oportunidades de uso da língua, mas a frequência de contato com o inglês continua sendo decisiva. Revisão de vocabulário, leitura, escuta e pequenas tarefas de produção distribuídas ao longo da semana ajudam a consolidar o que foi praticado ao vivo.',
    'self_study_p2', 'Por isso, eu considero o grupo pequeno especialmente eficiente quando a aula e o estudo autônomo são tratados como partes do mesmo processo.',
    'related_title', 'Leituras relacionadas',
    'related_link_1', 'Como funciona uma aula online em turma pequena?',
    'related_link_2', 'Aula particular ou em grupo?',
    'related_link_3', 'Como perder o medo de falar inglês?',
    'cta_title', 'Como funciona no TeacherFlavius.com',
    'cta_text', 'As aulas são online, ao vivo e organizadas em turmas de até quatro alunos, com material de apoio e orientação de estudos.',
    'cta_button', 'Ver detalhes do curso'
  ),
  now()
)
on conflict (page_key) do nothing;
